[SB-45] Fixed bug and changed tabs to spaces
MrRamka/github-web-client pull request #6
Opened 2020-11-09 20:57 UTC by MrRamka

2020-11-09 21:11 UTC, ydooG approved these changes
Чётко брат

2020-11-10 15:07 UTC, easydush requested changes

2020-11-10 15:07 UTC, easydush commented on src/App.tsx
> +    );
очень важное дело, прям офигеть, как
ты **_упал в моих глазах_**

2020-11-10 15:07 UTC, easydush commented on src/components/NavigationMenu/NavigationMenu.tsx
> +const {Sider} = Layout;
верни пробелы

2020-11-10 15:46 UTC, MrRamka commented on src/components/NavigationMenu/NavigationMenu.tsx
> +const {Sider} = Layout;
https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Operators/Destructuring_assignment
https://learn.javascript.ru/destructuring
![image](https://user-images.githubusercontent.com/41204824/98696605-0f584e00-2385-11eb-8613-789975416890.png)

В двух источниках без пробелов. Думаю это такой стандарт.

2020-11-10 15:49 UTC, MrRamka commented on src/App.tsx
> +    );
Задача состояла в увеличении читаемости кода при проверке другими разработчиками. Не вижу тут что-то плохого.

2020-11-10 18:59 UTC, easydush commented on src/App.tsx
> +    );
это нерационально в тот момент, когда даже основного функционала нет
ИМХО

2020-11-10 19:00 UTC, easydush commented on src/components/NavigationMenu/NavigationMenu.tsx
> +const {Sider} = Layout;
эта педантичность меня эмоционально сдавливает

2020-11-10 19:06 UTC, easydush approved these changes

2020-11-10 19:06 UTC, merged

2020-11-10 21:02 UTC, MrRamka commented on src/App.tsx
> +    );
Думаю это стоило сделать как можно раньше, пока кода не так много.